### ISSUE TITLE
Unable to delete a member in phpBB 3.3

### ISSUE THREAD

**Issue by SpIdErPiGgY1984** [oneall/social-login-phpbb#75]
I get this error when I try to delete a user from the forum

`Fatal error: Uncaught TypeError: Argument 1 passed to phpbb\auth\provider\db::__construct() must be an instance of phpbb\captcha\factory, instance of phpbb\db\driver\factory given, called in /var/www/vhosts/supportforum.be/httpdocs/cache/production/container_dbdbe80dc7030ae9bd39ee30cca82130.php on line 1515 and defined in /var/www/vhosts/supportforum.be/httpdocs/phpbb/auth/provider/db.php:69 Stack trace: #0 /var/www/vhosts/supportforum.be/httpdocs/cache/production/container_dbdbe80dc7030ae9bd39ee30cca82130.php(1515): phpbb\auth\provider\db->__construct() #1 /var/www/vhosts/supportforum.be/httpdocs/vendor/symfony/dependency-injection/Container.php(306): phpbb_cache_container->getAuth_Provider_OneallSocialloginService() #2 /var/www/vhosts/supportforum.be/httpdocs/phpbb/di/service_collection.php(57): Symfony\Component\DependencyInjection\Container->get() #3 /var/www/vhosts/supportforum.be/httpdocs/phpbb/di/service_collection_iterator.php(44): phpbb\di\service_collection->offsetGet() #4 /var/www/vhosts/supportforum.be/httpdoc in /var/www/vhosts/supportforum.be/httpdocs/phpbb/auth/provider/db.php on line 69`

PHP: 7.4.1
phpBB: 3.3.0-RC1

**Comment by SpIdErPiGgY1984** [comment]
Seems to be fixed in the new 4.6.2 version. Thank you :)
